const productActionType = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_BESTSELLER:'GET_BESTSELLER',
    GET_NOVELTY:'GET_NOVELTY',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    SEARCH_PRODUCT: 'SEARCH_PRODUCT'
}
export default productActionType;